name: Test RAG System

on: [push, pull_request]

jobs:
  test-rag:
    runs-on: ubuntu-latest

    env:
      MOCK_MODE: true 

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test document ingestion in mock mode
      run: |
        python -c "
        import os
        os.environ['MOCK_MODE'] = 'true'
        from rag_pipeline import load_and_split_documents, setup_chroma
        print('✅ Document loading and splitting works')
        docs = load_and_split_documents()
        print(f'✅ Loaded {len(docs)} document chunks')
        "

    - name: Start FastAPI app in background
      run: |
        python -m uvicorn main:app --host 127.0.0.1 --port 8000 &
        sleep 10

    - name: Test API endpoints
      run: |
        # Test health check
        curl -f http://127.0.0.1:8000/health 
        
        # Test RAG query endpoint
        curl -X POST "http://127.0.0.1:8000/ask" \
          -H "Content-Type: application/json" \
          -d '{"question": "What is this about?", "session_id": "test"}' \
          -f || echo "ASK endpoint failed"
        



    
